### ISSUE TITLE
1366x768 resolution gives a distorted screen image

### ISSUE THREAD

**Issue by hanslse** [bluewaysw/pcgeos-basebox#18]
### Are you using the latest Dosbox-Staging Version?

- [x] I have checked releases and am using the latest release.

### What Operating System are you using?

Linux x86_64

### If Other OS, please describe

Ubuntu

### Relevant hardware info

Intel Celeron Hasboro,

### Have you checked that no other similar issue already exists?

- [x] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When I change to 1366x768. All the DPI resolutions work flawlessly.

<img width="1366" height="768" alt="Image" src="https://github.com/user-attachments/assets/68fc0177-9fa9-4103-be3f-042e72d4c764" />

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Start Basebox and Geos
2. Change resolution from whatever to 1366x768
3.

### Your configuration

```ini

```

### Provide a Log

```text

```

### Code of Conduct & Contributing Guidelines

- [x] Yes, I agree.

**Comment by bluewaysw** [comment]
Potentially fixed in the latest basebox v2 update, please test the solution.

**Comment by hanslse** [comment]
The bus still persists for me. Added screen dump

<img width="1366" height="768" alt="Image" src="https://github.com/user-attachments/assets/1578f406-8e19-4075-b722-a460db91a71e" />

**Comment by hanslse** [comment]
Sorry, for the delay, the bug is fixed for me, the screen image is now normal, and the bug is fixed.
